---
title: "Data Manipulations"
output: html_notebook
---

```{r}
devtools::load_all()
library(readr)
library(dplyr)
library(ggplot2)
library(purrr)
library(tidyr)

# grab all the paths to the mutation files
all_mutation_files <- list.files(path = "../tmp_data/pop_runs/", 
                                 pattern = "*mutations.txt",
                                 full.names = T,
                                 recursive = T)

# grab a genome template file
genome_template_file <- list.files(path = "../tmp_data/pop_runs/",
                                   pattern = "*fullgenome.txt",
                                   full.names = T,
                                   recursive = T)[1]

mutations <- read_delim(all_mutation_files[1], delim=" ") %>% filter(rep == 0)
genome_template <- read_delim(genome_template_file, delim = " ") %>% select(position)
```


```{r}
#' Join template genome position to a single parameter
#' of mutations
#' 
#' The default output mutations doesn't include a value for 
#'  neutral positions as a way to save resources when simulations
#'  are running. This function joins on the template genome
#'  (essentially a template for the positions on the genome) to
#'  the mutation data so that each position per each generation 
#'  has a row. This may or may not be the appropriate method
#'  depending on how you plan to use the data next.
#'
#' @param mutation_df A data frame of mutations for a given 
#'  parameter set
#' @param template A data frame of all the positions on the 
#'  genome corresponding to the mutations
#' @param generation_var The variable in the `mutation_df`
#'  corresponding to the the output generation variable
#' @param param_vars A vector of parameter variable names in
#'  the `mutation_df` frame
#' @return An expanded mutation data frame with empty (neutral) 
#'  position rows
expand_genome_to_template <- function(mutation_df, template, generation_var, param_vars) {
  uniq_generations <- mutation_df %>% 
    dplyr::group_by({{ generation_var }}) %>% 
    dplyr::summarize() %>% dplyr::pull()
  
  purrr::map(uniq_generations, function(gen) {
    mutation_generation <- mutation_df %>% 
      dplyr::filter({{generation_var}} == gen)
    mutation_params <- mutation_df %>% 
      dplyr::select(c({{ param_vars }})) %>% head(1)
    mutation_without_params <- mutation_df %>% 
      dplyr::select(-c({{ param_vars }}))
    
    num_param_cols <- ncol(mutation_params)
    num_template_rows <- nrow(template)
    
    template_param_rows <- mutation_params %>% 
      dplyr::slice(rep(1:num_param_cols, each = num_template_rows))
    full_template <- dplyr::bind_cols(template, template_param_rows)
    dplyr::left_join(full_template, mutation_generation)
  }) %>% purrr::reduce(dplyr::bind_rows)
}

expand_genome_to_template(mutations, template = genome_template, generation_var = output_gen, param_vars = c(migr_rate, recomb_rate, mut_rate, fitness_width, n, output_gen, rep))

uniq_generations <- mutations %>% group_by(output_gen) %>% summarize() %>% pull()
map(uniq_generations, function(x) {
  mutation_generation <- mutations %>% filter(output_gen == x)
  mutation_params <- mutations %>% 
    select(c(migr_rate, recomb_rate, mut_rate,
             fitness_width, n, output_gen, rep)) %>%
    head(1)
  mutation_without_params <- mutations %>% select(-c(migr_rate, recomb_rate, mut_rate,
             fitness_width, n, output_gen))
  num_param_cols <- ncol(mutation_params)
  num_template_rows <- nrow(genome_template)
  template_param_rows <- mutation_params %>% slice(rep(1:num_param_cols, each = num_template_rows))
  template <- bind_cols(genome_template, template_param_rows)
  left_join(template, mutation_generation)
}) %>% reduce(bind_rows) %>% replace_na(list(select_coef = 0, p1_freq = 0, p2_freq = 0))
```

```{r}
?right_join
```


```{r}
devtools::load_all()
library(readr)
library(dplyr)
library(ggplot2)


file <- '../tmp_data/m1e-5_mu1e-6_r1e-6_sigsqr25_mutations.txt'
df <- read_delim(file, delim = ' ')

handle_stacked_mutations <- function(data, origin_var, effect_size_var, group_vars) {
  data %>%
    dplyr::group_by(dplyr::across({{ group_vars }})) %>%
    dplyr::filter({{ origin_var }} == min({{ origin_var }})) %>%
    dplyr::filter(abs({{ effect_size_var }}) == max(abs({{ effect_size_var }}))) %>%
    dplyr::ungroup()
}

find_diff_effect_size_freq_diff <- function(data, p1_freq_var, p2_freq_var, effect_size_var) {
  data %>% 
    dplyr::mutate(effect_size_freq_diff = ({{ p1_freq_var }} - {{ p2_freq_var }}) * {{ effect_size_var }})
}

find_effect_size_freq <- function(data, effect_size_var, freq_var) {
  data %>%
    dplyr::mutate(effect_size_freq = {{ effect_size_var }} * {{ freq_var }})
  
}

calculate_fst <- function(data, freq_var, group_vars) {
  fst_data <- data %>% 
    dplyr::mutate(twopq = 2 * (1- {{ freq_var }}) * {{ freq_var }} ) %>%
    dplyr::group_by(dplyr::across({{ group_vars }})) %>% 
    dplyr::summarize(hs = mean(twopq), ht = 2 * mean((1- {{ freq_var }})) * mean({{ freq_var }})) %>%
    dplyr::ungroup() %>% 
    dplyr::mutate(fst = (ht - hs)/ht)
  
  dplyr::left_join(data, fst_data)
    
}

  



df %>% filter(rep == 0) %>%
  handle_stacked_mutations(origin_var = origin_gen, effect_size_var = select_coef, 
                           group_vars = c(position, migr_rate, mut_rate, recomb_rate, 
                                          fitness_width, output_gen, rep)) %>% 
  find_diff_effect_size_freq_diff(p1_freq, p2_freq, select_coef) %>%
  create_population_pq(c(p1_freq, p2_freq)) %>% 
  find_effect_size_freq(effect_size_var = select_coef, freq_var = freq) %>%
  calculate_fst(freq, c(position, migr_rate, mut_rate, recomb_rate, fitness_width, output_gen, rep))


files <- c( "../tmp_data/good_runs/m1e-3_mu1e-6_r1e-6_sigsqr25_mutations.txt",
   "../tmp_data/good_runs/m1e-4_mu1e-6_r1e-6_sigsqr25_mutations.txt",
   "../tmp_data/good_runs/m1e-5_mu1e-6_r1e-6_sigsqr25_mutations.txt",
   "../tmp_data/good_runs/m1e-3_mu1e-6_r1e-6_sigsqr2_mutations.txt",
   "../tmp_data/good_runs/m1e-4_mu1e-6_r1e-6_sigsqr2_mutations.txt",
   "../tmp_data/good_runs/m1e-5_mu1e-6_r1e-6_sigsqr2_mutations.txt",
   "../tmp_data/good_runs/m1e-3_mu1e-6_r1e-6_sigsqr5_mutations.txt",
   "../tmp_data/good_runs/m1e-4_mu1e-6_r1e-6_sigsqr5_mutations.txt",
   "../tmp_data/good_runs/m1e-5_mu1e-6_r1e-6_sigsqr5_mutations.txt"
   
)
all_data <- purrr::map(files, function(x) {
  df <- readr::read_delim(x, " ")
  df %>% 
    filter(rep == 0) %>%
  handle_stacked_mutations(origin_var = origin_gen, effect_size_var = select_coef, 
                           group_vars = c(position, migr_rate, mut_rate, recomb_rate, 
                                          fitness_width, output_gen, rep)) %>% 
  find_diff_effect_size_freq_diff(p1_freq, p2_freq, select_coef) %>%
  create_population_pq(c(p1_freq, p2_freq)) %>% 
  find_effect_size_freq(effect_size_var = select_coef, freq_var = freq) %>%
  calculate_fst(freq, c(position, migr_rate, mut_rate, recomb_rate, fitness_width, output_gen, rep)) 
}) %>% purrr::reduce(dplyr::bind_rows) %>% dplyr::rename(m = migr_rate, mu = mut_rate, r = recomb_rate, sigsqr = fitness_width)

all_data %>% View()
all_data %>% filter( m == 1e-3 & mu == 1e-6 & r == 1e-6 & sigsqr == 25 & output_gen == 4000) %>% group_by(pop) %>% summarise(sum(effect_size_freq_diff))
jsonlite::write_json(all_data, "../tmp_data/genome_data.json")
```

```{r}


df %>% filter(rep == 0) %>%
  handle_stacked_mutations(origin_var = origin_gen, effect_size_var = select_coef, 
                           group_vars = c(position, migr_rate, mut_rate, recomb_rate, 
                                          fitness_width, output_gen, rep)) %>% 
  create_population_pq(c(p1_freq, p2_freq)) %>% 
  find_effect_size_freq(effect_size_var = select_coef, freq_var = freq) %>%
  group_by(migr_rate, mut_rate, recomb_rate, fitness_width, output_gen, pop) %>%
  summarize(summed = sum(effect_size_freq)) %>%
  ggplot(aes(x = output_gen, y = summed, color = pop, group= pop)) + geom_line()
# add p q values for each pop
pq_df <- df %>% filter(rep == 0) %>%
  handle_stacked_mutations(origin_var = origin_gen, effect_size_var = select_coef, 
                           group_vars = c(position, migr_rate, mut_rate, recomb_rate, 
                                          fitness_width, output_gen, rep)) %>% 
  create_population_pq(c(p1_freq, p2_freq)) 

# create a reference for popsize
pop_popsize <- tibble(pop = c(1, 2), pop_size=c(1000, 1000))


  

pq_df %>% 
  append_popsize(pop_popsize, pop, pop) %>% 
  filter(migr_rate == 1e-04 & mut_rate == 1e-06 & recomb_rate == 1e-06 & fitness_width == 5 & output_gen == 2500 & rep == 0 ) %>%
  group_by(position, migr_rate, mut_rate, recomb_rate, fitness_width, output_gen, rep, pop)  %>%filter(origin_gen == min(origin_gen)) %>%
  ungroup()

pq_df %>% 
  filter(migr_rate == 1e-05 & mut_rate == 1e-06 & recomb_rate == 1e-06 & fitness_width == 25 & output_gen == 2000 & rep == 0 ) %>%
  mutate(twopq = 2 * (1-freq) * freq ) %>%
  group_by(position, migr_rate, mut_rate, recomb_rate, fitness_width, output_gen, rep) %>% 
  summarize(hs = mean(twopq), ht = 2 * mean((1-freq)) * mean(freq)) %>%
  ungroup() %>% mutate(fst = (ht - hs)/ht)


p1 <- .9985
p2 <- 1
q1 <- 1 - p1
q2 <- 1 - p2
pbar <- (p1 + p2)/2
qbar <- (q1 + q2)/2
ht <- 2 * pbar * qbar

v1 <-2 * p1 * (1 - p1)
v2 <- 2 * p2 * (1 - p2)
hs <- (v1 + v2)/2

(ht - hs)/ht
```

```{r}
pq_df %>% 
  append_popsize(df = pop_popsize, left_popref = pop, right_popref = pop) %>%
  mutate(effect_size_freq = select_coef * q) %>%
  group_by(position, migr_rate, mut_rate, recomb_rate, fitness_width, output_gen, rep) %>%
  mutate(effect_size_freq_diff = )
```

```{r}
p1 <- read_delim("../tmp_data/m1e-3_mu1e-6_r1e-6_sigsqr5_genome1.txt", delim = " ")
p2 <- read_delim("../tmp_data/m1e-3_mu1e-6_r1e-6_sigsqr5_genome2.txt", delim = " ")

```
